version: '3.7'

services:
  ui:
    container_name: ui
    image: node:12.16.1-alpine3.11
    working_dir: /ws/ui
    entrypoint: /bin/sh -c 'tail -f'
    volumes:
    - .:/ws
    environment:
      VUE_APP_API_URL: https://personal-stalker-api.herokuapp.com

  api:
    container_name: api
    image: node:12.16.1-alpine3.11
    working_dir: /ws/api
    entrypoint: /bin/sh -c 'tail -f'
    volumes:
    - .:/ws

